### ISSUE TITLE
would be willing to take over maintence & support

### ISSUE THREAD

**Issue by dan987** [CozyCo/bank_routing#3]
Please add me to project.

**Comment by mgreensmith** [comment]
Hi Dan, thanks for the interest!

We're (Cozy) considering this project to be archived and unmaintained. There have been no code changes, issues filed, PRs or support requests in more than two years. We're not using this app internally, and we're not really interested in re-opening the project or being associated with its ongoing use.

However, there are a couple of active forks that are being used and somewhat maintained by others. https://github.com/BlinkerGit/bank_routing seems to be the most active one.

If you want to maintain and use this code, I'd encourage you to either contribute to one of the maintained forks, or fork it yourself and update/maintain your own version of the codebase. This is a perfect use case for GitHub's fork mechanism, IMO.

If you do fork this repo, or join forces with BlinkerGit, and we see that there's some real movement in updating and maintaining the code, I'd eventually be willing to add a note to the README that points people to an "official" maintained fork.

Thanks!

**Comment by dan987** [comment]
ok thanks
